config/routes.rb
Rails.application.routes.draw do
  get 'signup' => 'application#signup'
  get 'login' => 'application#login'
  get 'signout' => 'application#signout'

  scope '/api' do
    scope '/v1' do
      scope '/users' do
        post '/' => 'api/users#new'
        get '/' => 'api/users#index'
        get '/authenticate' => 'api/users#authenticate'

        scope '/:userId' do
          get '/' => 'api/users#show'
          put '/' => 'api/users#update'
          put '/order' => 'api/users#order'

          scope'/credit-cards' do
            get '/' => 'api/credit_cards#index'

            scope '/:credit_card_id' do
              get '/' => 'api/credit_cards#show'
              put '/' => 'api/credit_cards#update'
              get '/charge/:amount' => 'api/credit_cards#charge'
            end
          end
        end
      end
    end
  end

  root 'application#home'

end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base

  #associations
  belongs_to :users

  #validations
  validates :cardNumber, presence: true
  validates :expirationMonth, presence: true
  validates :expirationYear, presence: true
  validates :cvc, presence: true
  validates :stripe_token, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  #associations
  has_many :credit_cards, dependent: :destroy

  validates :email, presence: true, uniqueness: { case_sensitive: false }
end

app/controllers/api/credit_cards_controller.rb
module Api
  class CreditCardsController < ApplicationController
    include ApplicationHelper
    include CreditCardsHelper

    before_action  :get_user

    def index
      if @user
        render json: @user.credit_cards.to_json(except: [:cvc])
      else
        render json: { errors: ["invalid user: #{params[:userId]}"] }.to_json, status: 400
      end
    end

    def show
      if @user
        render json: get_credit_card.to_json(except: [:cvc])
      else
        render json: { errors: ["invalid user: #{params[:userId]}"] }.to_json, status: 400
      end
    end

    def new
      if @user
        credit_card = create_credit_card(@user, params);

        if credit_card.valid?
          #save credit card data
          credit_card.save()
          @user.credit_cards.push(credit_card)

          render json: credit_card.to_json([:stripe_token])
        else
          errors = convert_error_hash_to_array(credit_card.errors)
          render json: { errors: errors }.to_json, status: 400
        end

      else
        render json: { errors: ["invalid user: #{params[:userId]}"] }.to_json, status: 400
      end
    end

    def update
    end

    def charge
      if @user
        credit_card =  get_credit_card()

        if credit_card
          #call stripe api to charge card
          begin
            charge_card(credit_card, params[:amount].to_i, params[:charge_description])

            render json: { success: true }
          rescue Exception => e
            render json: {errors: ["unable to charge due to: #{e}"] }.to_json, status: 500
          end
        else
          render json: { errors: ["invalid credit card: #{params[:credit_card_id]}"] }.to_json, status: 400
        end
      else
        render json: { errors: ["invalid user: #{params[:userId]}"] }.to_json, status: 400
      end
    end

    private
      def get_user
        if User.exists?(params[:userId])
          @user = User.find(params[:userId])
        end
      end

      def get_credit_card
        @user.credit_cards.find(params[:credit_card_id])
      end
  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController
    include ApplicationHelper
    include CreditCardsHelper

    skip_before_action :verify_authenticity_token

    PRICE_HASH = {1 => 5999, 2 => 7999}

    def new
      #create user and credit card
      user = create_user()

      if user.valid?
        begin
          credit_card = create_credit_card(params[:creditCard])

          if credit_card.valid?
            user.save()
            credit_card.save()
            user.credit_cards.push(credit_card)

            #set user cookie
            set_user_cookie(user)

            #return created json
            render json: user.as_json(except: [:password])
          else
            errors = convert_error_hash_to_array(credit_card.errors)
            render json: { errors: errors }.to_json, status: 400
          end

        rescue Exception => e
          render json: {errors: ["unable to charge due to: #{e}"] }.to_json, status: 500
        end

      else
        errors = convert_error_hash_to_array(user.errors)
        render json: { errors: errors }.to_json, status: 400
      end

    end

    def index
      render json: User.all.to_json(except: [:password])
    end

    def show
      userId = params[:userId]

      if User.exists?(id: userId)
        user = User.find(userId)
        render json: user.to_json(except: [:password], include: :credit_cards)
      else
        render json: { errors: ["user with id: #{userId} is not found"] }.to_json, status: 404
      end
    end

    def authenticate
      email = params[:email]
      password = params[:password]

      if User.where(email: email, password: password).present?
        user = User.where(email: email, password: password).first
        set_user_cookie(user)
        render json: user.to_json
      else
        render json:{ errors: ["invalid credentials"] }.to_json, status: 401
      end
    end

    def update
      userId = params[:userId]
    end

    def order
      userId = params[:userId]

      if User.exists?(id: userId)
        user = User.find(userId)
        credit_card = user.credit_cards.first

        begin
          charge_card(credit_card,  PRICE_HASH[user.planId] , "Order for #{Time.now}")
          render json: { success: true }
        rescue Exception => e
          render json: {errors: ["unable to charge due to: #{e}"] }.to_json, status: 500
        end
      else
        render json: { errors: ["user with id: #{userId} is not found"] }.to_json, status: 404
      end

    end

    private
      def create_user
        User.new(email: params[:email], password: params[:password],
                 firstName: params[:firstName], lastName: params[:lastName],
                 address_line_1: params[:address][:addressLine1],
                 address_line_2: params[:address][:addressLine2],
                 city: params[:address][:city],state: params[:address][:state],
                 zip: params[:address][:zip],planId: params[:planId])
      end

      def set_user_cookie(user)
        cookies[:user] = { value: user.to_json(except: [:password]), expires: 30.minute.from_now }
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def signup
  end

  def home
  end

  def login

  end

  def signout
    cookies.delete :user
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def convert_error_hash_to_array(error_object)
    errors = []

    error_object.each do |key|
      error_object[key].each do |attr_error|
        errors.push("#{key}: #{attr_error}")
      end
    end

    errors
  end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
  def create_credit_card(credit_card_info)
    customer = Stripe::Customer.create(
      :source => credit_card_info[:token],
      :description => "card for #{credit_card_info[:name]}"
    )

    CreditCard.new(cardNumber: credit_card_info[:number],
                   expirationMonth: credit_card_info[:exp_month],
                   expirationYear: credit_card_info[:exp_year],
                   cvc: credit_card_info[:cvc],
                   stripe_token: customer.id);

  end
  
  def charge_card(credit_card, amount, charge_description)
    begin
      if amount >= 50
        charge = Stripe::Charge.create(
          :amount => amount,
          :currency => "usd",
          :customer => credit_card[:stripe_token],
          :description => charge_description
        )

        return charge
      else
        raise "invalid charge amount: #{amount}, please provide amount in cents (i.e 100 is a $1), and at least 50 cents"
      end
    rescue Stripe::CardError => e
      raise "unable to charge due to: #{e}"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.erb
<div ng-controller="accountCtrl">
  <!-- <p>we support payment request :: {{hasPaymentRequestSupport}}</p> -->
  <div class="jumbotron welcome-jumbo">
    <h1>{{message}}</h1>
    <p>Discover a better way to cook</p>
    <p ng-hide="user"><a class="btn btn-primary btn-lg" ng-click="redirectToSignup()">Learn more</a></p>
    <p ng-show="user"><a class="btn btn-primary btn-lg" ng-click="order()">Order Now!</a></p>
  </div>
  <div class="alert alert-dismissible alert-success order-alert"  hidden="true">
    <p><strong>Congratulations!</strong> Your order is on its way</p>
  </div>
  <div class="alert alert-dismissible alert-danger error-alert" hidden="true">
    <span class="error-message"></span>
  </div>

  <!-- learn more section -->
  <div class="col-lg-12 row">

    <!-- learn more - receipes -->
    <div class="col-lg-4 ">
      <div class="learn-more-box">
        <figure>
          <figcaption class="image-caption learn-more-image-caption">
            <span>
              <img src="/assets/marketing/recipe-cards.png" class="learn-more-logo">
              Original Recipes Weekly
            </span>
          </figcaption>
          <img src="/assets/marketing/learn-info-pod-recipes.jpg" class="learn-more-image">
          <figcaption class="trailing-text">
            <ul>
              <li>Discover exciting, seasonal recipes created by our culinary team and renowned guest chefs</li>
              <li>Recipes never repeated in the same year</li>
              <li>500-800 calories per serving</li>
            </ul>
          </figcaption>
        </figure>
      </div>
    </div>

    <!-- learn more - ingredients -->
    <div class="col-lg-4">
      <div class="learn-more-box">
        <figure>
          <figcaption class="image-caption learn-more-image-caption">
            <span>
              <img src="/assets/marketing/ingredients.png" class="learn-more-logo">
              <strong>Fresh Ingredients</strong>
            </span>
          </figcaption>
          <img src="/assets/marketing/learn-info-pod-ingredients.jpg" class="learn-more-image">
          <figcaption class="trailing-text">
            <ul>
              <li>Specialty ingredients that are fresher than the supermarket</li>
              <li>Ingredients are perfectly pre-measured so there’s no waste</li>
              <li>5Meats naturally raised on antibiotic- and hormone-free diets</li>
            </ul>
          </figcaption>
        </figure>
      </div>
    </div>

    <!-- learn more - delivery -->
    <div class="col-lg-4">
      <div class="learn-more-box">
        <figure>
          <figcaption class="image-caption learn-more-image-caption">
            <span>
              <img src="/assets/marketing/shipping-truck.png" class="learn-more-logo">
              <strong>Convenient Delivery</strong>
            </span>
          </figcaption>
          <img src="/assets/marketing/learn-info-pod-delivery.jpg" class="learn-more-image">
          <figcaption class="trailing-text">
            <ul>
              <li>Free delivery nationwide</li>
              <li>Choose a delivery day that best fits your schedule</li>
              <li>Ingredients arrive in a refrigerated box so food stays fresh even if you’re not home when we deliver</li>
            </ul>
          </figcaption>
        </figure>
      </div>
    </div>
  </div>
</div>

app/views/application/login.html.erb
<div ng-controller='signUpCtrl'>
  <legend><h1>Login</h1></legend>
  <form name="loginForm" id="login-form" >
    <div class="alert alert-dismissible alert-danger" hidden="true">
      <span class="payment-errors"></span>
    </div>
    <fieldset>
      <div class="form-group">
             <div class="input-group input-group-lg">
               <input type="text" required class="form-control" required placeholder="Email" ng-model="user.email"/>
               <span class="input-group-addon"><i class="fa fa-user text-primary"></i></span>
             </div>
           </div>
           <div class="form-group">
             <div class="input-group input-group-lg">
               <input type="password" required class="form-control" required placeholder="Password" ng-model="user.password"/>
               <span class="input-group-addon"><i class="fa fa-lock text-primary"></i></span>
             </div>
           </div>

           <div class="form-group">
             <div class="input-group input-group-lg no-padding">
               <div class="col-md-6">
                 <button class="btn btn-lg btn-success btn-login"  ng-disabled="loginForm.$invalid" ng-click="login(user)">Login</button>
               </div>
             </div>
           </div>

    </fieldset>
  </form>
</div>

app/views/application/signup.html.erb
<div ng-controller='signUpCtrl'>
  <legend><h1>Sign up</h1></legend>
  <h4>payment request support::{{hasPaymentRequestSupport}}</h4>
  <form name="signupForm" id="sign-up-form">
    <div class="alert alert-dismissible alert-danger" hidden="true">
      <span class="payment-errors"></span>
    </div>

      <!-- select meal plan section -->
      <div class="col-lg-12 row">
        <h4 class="form-subheader">Select Your Meal Plan:</h4>
      </div>

      <div class="col-lg-12 row">
        <div class="col-lg-6">
          <figure>
          <img src="/assets/marketing/2-person.jpg" class="plan-image" ng-class="{selected_plan_image: user.planId == 1}" ng-click="changePlan(1)">
          <figcaption class="image-caption meal-plan-image-caption">2-Person Meal Plan: $59.99</figcaption>
          </figure>
        </div>
        <div class="col-lg-6">
          <figure>
          <img src="/assets/marketing/family.jpg" class="plan-image" ng-class="{selected_plan_image: user.planId == 2}" ng-click="changePlan(2)">
          <figcaption class="image-caption meal-plan-image-caption">Family Meal Plan: $79.99</figcaption>
          </figure>
        </div>
      </div>

      <!-- check flow with payment request -->
      <div ng-show="hasPaymentRequestSupport">
        <div class="col-lg-12 row">
          <div class="col-lg-6"></div>
          <div class="col-lg-6">
            <button class="btn btn-primary btn-sign-up" ng-click="signUpWithPaymentRequest()">sign up</button>
          </div>
        </div>
      </div>

      <!-- legacy checkout flow -->
      <div ng-hide="hasPaymentRequestSupport" class="ng-hide">
        <!-- personal information section -->
        <div class="col-lg-12 row">
          <h4 class="form-subheader">Personal Information:</h4>
        </div>

        <div class="col-lg-12 row">
          <div class="col-lg-6">
            <div class="form-group">
              <label for="email" class="col-lg-4 control-label">Email:</label>
              <div class="col-lg-8">
                <input type="text" class="form-control" required name="email" ng-model="user.email"></input>
              </div>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="form-group">
              <label for="password" class="col-lg-4 control-label">Password:</label>
              <div class="col-lg-8">
                <input type="password" class="form-control" required name="password" ng-model="user.password"></input>
              </div>
            </div>
          </div>
        </div>

        <div class="col-lg-12 row">
          <div class="col-lg-6">
            <div class="form-group">
              <label for="firstName" class="col-lg-4 control-label">First Name:</label>
              <div class="col-lg-8">
                <input type="text" class="form-control" required name="firstName" ng-model="user.firstName"></input>
              </div>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="form-group">
              <label for="lastName" class="col-lg-4 control-label">Last Name:</label>
              <div class="col-lg-8">
                <input type="text" class="form-control" required name="lastName" ng-model="user.lastName"></input>
              </div>
            </div>
          </div>
        </div>

        <div class="col-lg-12 row">
          <h4 class="form-subheader">Shipping Information:</h4>
        </div>

        <div class="col-lg-12 row">
          <div class="col-lg-6">
            <div class="form-group">
              <label for="address1" class="col-lg-4 control-label">Address Line 1:</label>
              <div class="col-lg-8">
                <input type="text" class="form-control" required name="address1" ng-model="user.address.addressLine1"></input>
              </div>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="form-group">
              <label for="address2" class="col-lg-4 control-label">Address Line 2:</label>
              <div class="col-lg-8">
                <input type="text" class="form-control" name="address2" ng-model="user.address.addressLine2"></input>
              </div>
            </div>
          </div>
        </div>

        <div class="col-lg-12 row">
          <div class="col-lg-6">
            <div class="form-group">
              <label for="city" class="col-lg-4 control-label">City:</label>
              <div class="col-lg-8">
                <input type="text" class="form-control" required name="city" ng-model="user.address.city"></input>
              </div>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="form-group">
              <label for="state" class="col-lg-4 control-label">State:</label>
              <div class="col-lg-8">
                <input type="text" class="form-control" required name="state" ng-model="user.address.state"></input>
              </div>
            </div>
          </div>

          <div class="col-lg-6">
            <div class="form-group">
              <label for="zip" class="col-lg-4 control-label">Zip:</label>
              <div class="col-lg-8">
                <input type="text" class="form-control" required name="zip" ng-model="user.address.zip"></input>
              </div>
            </div>
          </div>
        </div>

        <!-- credit card information section -->
        <div class="col-lg-12 row">
          <h4 class="form-subheader">Credit Card Information:</h4>
        </div>

        <div class="col-lg-12 row">
          <div class="col-lg-6">
            <div class="form-group">
              <label for="cardNumber" class="col-lg-4 control-label">Card Number:</label>
              <div class="col-lg-8">
                <input type="text" class="form-control" name="cardNumber" maxlength="16" size="16" data-stripe="number" ng-model="user.creditCard.number"></input>
              </div>
            </div>
          </div>
          <div class="col-lg-6">
            <div class="form-group">
              <label class="col-lg-4 control-label">Expiration (MM/YY)</label>
              <div class="col-lg-8">
                <input type="text" class="form-control cc-exp-field" maxlength="2" size="2" data-stripe="exp_month" name="expirationMonth" ng-model="user.creditCard.exp_month">
                <span>/</span>
                <input type="text" class="form-control cc-exp-field" maxlength="2" size="2" data-stripe="exp_year" name="expirationYear" ng-model="user.creditCard.exp_year">
              </div>
            </div>
          </div>
        </div>

        <div class="col-lg-12 row">
          <div class="col-lg-6">
            <div class="form-group">
              <label for="cvc" class="col-lg-4 control-label">CVC:</label>
              <div class="col-lg-8">
                <input type="text" class="form-control" name="cvc" data-stripe="cvc" ng-model="user.creditCard.cvc"></input>
              </div>
            </div>
          </div>
        </div>

        <div class="col-lg-12 row">
          <div class="col-lg-6"></div>
          <div class="col-lg-6">
            <button class="btn btn-primary btn-sign-up" ng-disabled="signupForm.$invalid" ng-click="signUp()">submit</button>
          </div>
        </div>
      </div>

  </form>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <i class="fa fa-facebook" aria-hidden="true"></i>
    <i class="fa fa-twitter" aria-hidden="true"></i>
    <i class="fa fa-instagram" aria-hidden="true"></i>
    <i class="fa fa-pinterest-square" aria-hidden="true"></i>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to image_tag("logo/blue-apron-logo.png", width: 60), root_path, id: "logo", class: "navbar-brand"%>

      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="navbar-main">
      <ul class="nav navbar-nav">
        <% if cookies[:user] %>
          <li><%= link_to "Sign out", signout_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Login", login_path %></li>
        <% end %>

      </ul>

    <div>
  </div>
</nav>
<p id="notice"><%=  notice %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="blueapron">
<head>
  <title>Blue Apron - Payment</title>

  <!--bootstrap and styles-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Slab" >
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" >

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0-rc.0/angular-resource.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0-rc.0/angular-route.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0-rc.0/angular-cookies.min.js"></script>

  <!--stripe-->
  <script src="https://js.stripe.com/v2/" type="text/javascript"></script>
  <script type="text/javascript">
    Stripe.setPublishableKey('pk_test_2wyLmRzS2lIYIuMlkbbIjuxL');
  </script>

  <!--rails app-->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'signup_controller', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'account_controller', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag 'ba.ico' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>

  <div class="content-container container">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>
</body>
</html>

app/views/users/index.html.erb
<div class="jumbotron welcome-jumbo">
  <h1>Welcome!</h1>
  <p>Discover a better way to cook</p>
  <p><a class="btn btn-primary btn-lg">Learn more</a></p>
</div>